package com.example.coursematchdaddy.clean_architecture_layers.use_cases.classes;

import com.example.coursematchdaddy.clean_architecture_layers.entities.interfaces.user_class_imports_implementations.AdministrationUserInterface;
import com.example.coursematchdaddy.clean_architecture_layers.entities.interfaces.user_class_imports_implementations.GuestUserInterface;
import com.example.coursematchdaddy.clean_architecture_layers.entities.interfaces.user_class_imports_implementations.LoggedInUserInterface;

public class Login implements LoggedInUserInterface, GuestUserInterface, AdministrationUserInterface {
}
