package com.example.coursematchdaddy.clean_architecture_layers.use_cases.classes;

import com.example.coursematchdaddy.clean_architecture_layers.entities.interfaces.course_class_imports.ArtsAndSciencesCourseInterface;
import com.example.coursematchdaddy.clean_architecture_layers.entities.interfaces.course_class_imports.ClosedEnrollmentCourseInterface;
import com.example.coursematchdaddy.clean_architecture_layers.entities.interfaces.course_class_imports.OpenEnrollmentCourseInterface;
import com.example.coursematchdaddy.clean_architecture_layers.entities.interfaces.program_class_imports.Type1ProgramInterface;
import com.example.coursematchdaddy.clean_architecture_layers.entities.interfaces.program_class_imports.Type2ProgramInterface;
import com.example.coursematchdaddy.clean_architecture_layers.entities.interfaces.program_class_imports.Type3ProgramInterface;

public class RecommendationAlgorithm implements ArtsAndSciencesCourseInterface, OpenEnrollmentCourseInterface, ClosedEnrollmentCourseInterface, Type1ProgramInterface, Type2ProgramInterface, Type3ProgramInterface {
}
