package com.example.coursematchdaddy.clean_architecture_layers.presenters.classes;

import com.example.coursematchdaddy.clean_architecture_layers.use_cases.interfaces.recommendationalgorithm_class_imports_implementations.ViewCoursesRecommendationsInterface;

public class CourseRecommendationsPresenter implements ViewCoursesRecommendationsInterface {
}
