package com.example.coursematchdaddy.clean_architecture_layers.presenters.classes;

import com.example.coursematchdaddy.clean_architecture_layers.use_cases.interfaces.recommendationalgorithm_class_imports.ViewCourseDataInterface;

public class CoursePresenter implements ViewCourseDataInterface {
}
